### ISSUE TITLE
Error with "the 'configparser' distribution was not found and is required by flake8"

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda-forge/flake8-feedstock#3]
We got this error by adding conda-forge to the channels on pandas' travis CI. See https://github.com/pydata/pandas/pull/13662#issuecomment-241384308. The error when using flake8:

```
pkg_resources.DistributionNotFound: The 'configparser' distribution was not found and is required by flake8
```

Not installing flake8 from conda-forge solved the problem (by not adding the channel conda-wide, but only install the specific packages from conda-forge with `-c conda-forge`, in our case we installed the matplotlib beta from conda-forge).

Not sure what is going on, and I also did not yet try to reproduce this error locally.

**Comment by croth1** [comment]
I did not pay enough attention to the dependencies. I linked pushed new PR which should fix this.
